### ISSUE TITLE
Read the entire commit message, not just the first line

### ISSUE THREAD

**Issue by darinmorrison** [autosuite/autoskip#4]
I've forked this action and tried to use it as described in the README:

```yaml
jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: interfaces-rs/skip-commit@master
        with:
          commit-filter: skip-ci
          always-allow-tags: true
          ref: ${{ github.ref }}
```

I've tried to test the action with a commit with a message like so:

```
Some commit message.

[skip-ci]
```

However, the action doesn't seem to trigger. I've also tried just with `skip-ci` without the enclosing square brackets.

Am I missing something? It might help to see a complete example with a known working filter and triggering message.

Anyway, thanks for making this!

**Comment by paced** [comment]
Hi @darinmorrison, looks like you're using somebody else's fork of this repo. Try `uses: autosuite/autoskip@master` instead of `interfaces-rs/skip-commit@master`.

Also, it's worth checking out [this issue](https://github.com/veggiemonk/skip-commit/issues/5) upstream. I will add this to the `README.md` file as well as it's significantly more elegant to use this than fail a build if something is found in the commit message.

**Comment by paced** [comment]
Whoops, I didn't read through your issue description thoroughly enough. Looks like you forked it yourself. I'll investigate!

**Comment by paced** [comment]
This is a bug, it works on first lines only. I said I wasn't going to maintain this anymore, but a lot of my other Actions also read the commit messages and a lot of users will probably want to hide the square brackets stuff. I'll get working on a fix before this weekend's over.

Seems to work on the commit message: "[skip-ci] stuff here". See [this workflow run](https://github.com/autosuite/autoskip/commit/b7c6e770192fea16ff4df967756d01a3897bf4eb/checks?check_suite_id=321851953).

**Comment by paced** [comment]
@darinmorrison This has been fixed in the latest version, please pull from my fork to get the necessary changes. See the [build here](https://github.com/autosuite/autoskip/commit/9d3b3d1bb2f2c62dd25645bb5370e01becbecb36/checks?check_suite_id=321890411).

As the documentation states, the failure is intentional as exit code 78 no longer cleanly exits a build without failure.

Please close this issue if it solves your question or raise any more concerns if you have them. Otherwise, I'll close it in a few days.

**Comment by darinmorrison** [comment]
Thanks for looking in to this and fixing it! I haven't had a chance to test it yet but given that you identified the likely cause of my problem, I'll go ahead and close this. (If I still have issues with it I'll follow up).
